/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jackredwine' at '6/20/15 6:18 PM' with Gradle 2.4
 *
 * @author jackredwine, @date 6/20/15 6:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
